// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameClerkUser = "clerk_users"

// ClerkUser mapped from table <clerk_users>
type ClerkUser struct {
	ID             string `gorm:"column:id;type:character varying(128);primaryKey" json:"id"`
	LinkedIdentity string `gorm:"column:linked_identity;type:text;not null" json:"linked_identity"`
}

// TableName ClerkUser's table name
func (*ClerkUser) TableName() string {
	return TableNameClerkUser
}
