// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	ID        string         `gorm:"column:id;type:character(26);primaryKey" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone" json:"deleted_at"`
	ParentID  *string        `gorm:"column:parent_id;type:text" json:"parent_id"`
	FileName  *string        `gorm:"column:file_name;type:text" json:"file_name"`
	MimeType  string         `gorm:"column:mime_type;type:text;not null" json:"mime_type"`
	Data      []uint8        `gorm:"column:data;type:bytea;not null" json:"data"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
